# Generated by Django 4.2 on 2023-04-16 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounter', '0002_alter_operation_customer_alter_operation_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounter.customer'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='source',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='operation',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounter.supplier'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
