# Generated by Django 4.2 on 2023-04-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounter', '0003_alter_operation_customer_alter_operation_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='source',
            new_name='is_bank',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='type',
            new_name='is_sale',
        ),
    ]
