# Generated by Django 4.2 on 2023-06-08 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounter', '0005_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounter.item'),
        ),
        migrations.AddField(
            model_name='operation',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
