# Generated by Django 4.2 on 2023-06-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounter', '0006_operation_item_operation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='is_payment',
            field=models.BooleanField(default=False),
        ),
    ]
