# Generated by Django 4.2 on 2023-06-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounter', '0007_operation_is_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bin',
            field=models.CharField(default='0000', max_length=25),
        ),
    ]
