# Generated by Django 4.2 on 2023-06-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounter', '0009_contract_operation_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='name',
            field=models.CharField(default='Без названия', max_length=60),
        ),
    ]
