# Generated by Django 4.2 on 2023-06-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounter', '0010_contract_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
