# Generated by Django 4.2 on 2023-06-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounter', '0012_alter_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='contract_file',
            field=models.FileField(null=True, upload_to='invoices/'),
        ),
    ]
